### ISSUE TITLE
Type errors on nullable in Typescript 4.9

### ISSUE THREAD

**Issue by estyrke** [hayes/pothos#773]
```typescript

export class Group {
  // <snip>

  get children() {
    return GROUP_DEFINITIONS[<GroupName>this.name];
  }

  // <snip>
}

export const GroupType = builder.objectRef<Group>("Group");

GroupType.implement({
  fields: (t) => ({
    children: t.exposeStringList("children", {
      nullable: false, // <-- Type error here
    }),
  }),
});
```

I get a typescript error on the `nullable` line:
```
error TS2322: Type 'false' is not assignable to type '(false & ExposeNullableOption<ExtendDefaultTypes<[... builder types omitted for brevity ...]>, ["String"], Group, "children">) | undefined'.
```

I first noticed this after upgrading typescript from 4.8.4 to 4.9.4, but it might possibly be unrelated. Any help appreciated! At runtime the code works, same as before.

**Comment by estyrke** [comment]
I just verified - the error does not appear in TS 4.8.4, and it is still there in 4.9.5.

**Comment by estyrke** [comment]
If I change the nullable to `nullable: { items: true, list: false }`, the error becomes (the possibly more clarifying)
```
error TS2322: Type '{ items: true; list: false; }' is not assignable to type '({ items: true; list: false; } & true) | ({ items: true; list: false; } & { items: boolean; list: boolean; } & true) | undefined'.
  Type '{ items: true; list: false; }' is not assignable to type '{ items: true; list: false; } & { items: boolean; list: boolean; } & true'.
    Type '{ items: true; list: false; }' is not assignable to type 'true'
```

**Comment by hayes** [comment]
I tried to reproduce this issue, but have not been able to:

https://stackblitz.com/edit/typescript-rmf22w?file=index.ts,tsconfig.json

This sees specific to types not included in the example above

**Comment by estyrke** [comment]
Thanks for looking into it! After trying for quite a while to extend the stackblitz enough without succeeding, I finally realized that explicitly typing the return value of `Group.children` to `string[]` resolves the issue.

I'm a bit curious why the stackblitz differs from my code though.  I tried 
```typescript
export class Group {
  get children(): ("a" | "b")[] {
    return ["a"]; //GROUP_DEFINITIONS[<GroupName>this.name];
  }
}

type Foo = ExposeNullableOption<
  PothosSchemaTypes.ExtendDefaultTypes<{}>,
  ["String"],
  Group,
  "children"
>;
```

In the "real" code (using VS code tooltips), Foo resolves to 
```typescript
type Foo = FieldNullability<["String"]> & (true | {
    items: boolean;
    list: true;
} | {
    items: boolean;
    list: true;
})
```

But in stackblitz it's 
```typescript
type Foo = FieldNullability<["String"]> & (boolean | {
    items: boolean;
    list: boolean;
} | {
    items: boolean;
    list: boolean;
})
```

I'm no typescript expert, but It seems like this could be a typescript bug. 
```typescript

type Bar = Group["children"] extends NonNullable<Group["children"]>
  ? true
  : false;
```
resolves to `true` in both my local editor and in stackblitz, which I *think* means that nullable should be allowed to be false.

**Comment by hayes** [comment]
Thanks for the detailed reply!  Figured out the issue, and fixed it here: https://github.com/hayes/pothos/commit/3021b43a55a45f1126ce96ffdc1d1c5ed59bc4e7

**Comment by estyrke** [comment]
Works like a charm! Thanks for persisting!
